ignoredBuiltDependencies:
  - msw
  - puppeteer
  - sharp

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - husky
  - sharp
  - unrs-resolver
patchedDependencies:
  react-router@8.3.0: patches/react-router@8.3.0.patch
